services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: collec_club
      POSTGRES_USER: collec
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U collec -d collec_club']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
