/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    customers: Customer;
    'media-types': MediaType;
    'media-items': MediaItem;
    'external-ids': ExternalId;
    collections: Collection;
    'collection-items': CollectionItem;
    pathways: Pathway;
    'pathway-steps': PathwayStep;
    'user-watched-items': UserWatchedItem;
    'user-collection-progress': UserCollectionProgress;
    'user-pathway-progress': UserPathwayProgress;
    badges: Badge;
    'user-badges': UserBadge;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    collections: {
      items: 'collection-items';
    };
    pathways: {
      steps: 'pathway-steps';
    };
  };
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'media-types': MediaTypesSelect<false> | MediaTypesSelect<true>;
    'media-items': MediaItemsSelect<false> | MediaItemsSelect<true>;
    'external-ids': ExternalIdsSelect<false> | ExternalIdsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    'collection-items': CollectionItemsSelect<false> | CollectionItemsSelect<true>;
    pathways: PathwaysSelect<false> | PathwaysSelect<true>;
    'pathway-steps': PathwayStepsSelect<false> | PathwayStepsSelect<true>;
    'user-watched-items': UserWatchedItemsSelect<false> | UserWatchedItemsSelect<true>;
    'user-collection-progress': UserCollectionProgressSelect<false> | UserCollectionProgressSelect<true>;
    'user-pathway-progress': UserPathwayProgressSelect<false> | UserPathwayProgressSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    'user-badges': UserBadgesSelect<false> | UserBadgesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  /**
   * Identifiant public unique, 3 à 30 caractères.
   */
  pseudo: string;
  /**
   * Désactiver ce compte pour empêcher la connexion.
   */
  disabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-types".
 */
export interface MediaType {
  id: number;
  /**
   * Identifiant stable, ne pas modifier après création.
   */
  slug: string;
  /**
   * Libellé affiché (ex: Film, Série)
   */
  label: string;
  display_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-items".
 */
export interface MediaItem {
  id: number;
  /**
   * Titre FR. Modifiable manuellement - un re-sync TMDB écrasera cette valeur.
   */
  title: string;
  /**
   * Identifiant URL unique. Auto-généré depuis le titre + année si vide.
   */
  slug?: string | null;
  original_title?: string | null;
  year?: number | null;
  /**
   * Date de sortie (AAAA-MM-JJ). Utilisée pour le tri chronologique dans les collections.
   */
  release_date?: string | null;
  /**
   * Minutes pour les films, nombre de saisons pour les séries.
   */
  duration?: number | null;
  /**
   * Synopsis. Modifiable manuellement - un re-sync TMDB écrasera cette valeur.
   */
  synopsis?: string | null;
  /**
   * URL absolue image.tmdb.org. Modifiable manuellement - un re-sync TMDB écrasera cette valeur.
   */
  poster_url?: string | null;
  media_type: number | MediaType;
  tmdb_id?: number | null;
  imdb_id?: string | null;
  director?: string | null;
  /**
   * Acteurs principaux, séparés par virgule (10 max).
   */
  cast?: string | null;
  source_of_truth?: 'tmdb' | null;
  source_last_synced_at?: string | null;
  source_expires_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-ids".
 */
export interface ExternalId {
  id: number;
  media_item: number | MediaItem;
  provider: 'tmdb' | 'imdb';
  external_id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  /**
   * Identifiant URL unique, format kebab-case (ex: filmographie-villeneuve).
   */
  slug: string;
  title: string;
  /**
   * Courte description affichée dans le listing. 140 caractères maximum.
   */
  short_description: string;
  /**
   * Note éditoriale longue. Recommandée pour les collections non factuelles (mouvements, thématiques).
   */
  editorial_note?: string | null;
  type:
    | 'filmography_complete'
    | 'filmography_studio'
    | 'saga'
    | 'franchise'
    | 'movement'
    | 'subgenre'
    | 'prize_complete'
    | 'prize_edition'
    | 'national_cinema'
    | 'thematic';
  /**
   * Niveau requis pour apprécier la collection.
   */
  accessibility_level: 'accessible' | 'curieux' | 'cinephile';
  /**
   * URL absolue de l'image de couverture.
   */
  cover_image_url?: string | null;
  /**
   * Collection ouverte (ajout continu d'oeuvres) vs fermée (figée).
   */
  is_open?: boolean | null;
  /**
   * Rendre la collection visible sur le site public.
   */
  is_published?: boolean | null;
  /**
   * Parcours directement lié à cette collection.
   */
  linked_pathway?: (number | null) | Pathway;
  display_order?: number | null;
  items?: {
    docs?: (number | CollectionItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways".
 */
export interface Pathway {
  id: number;
  /**
   * Identifiant URL unique, format kebab-case (ex: nouvelle-vague-naissance-cinema).
   */
  slug: string;
  title: string;
  /**
   * Précise l'angle sans répéter le titre.
   */
  subtitle?: string | null;
  /**
   * 200 à 500 mots. Angle éditorial et promesse d'expérience.
   */
  introduction: string;
  type: 'historical' | 'author' | 'thematic' | 'national' | 'genre' | 'blockbuster';
  /**
   * Niveau requis pour apprécier le parcours.
   */
  accessibility_level: 'accessible' | 'curieux' | 'cinephile';
  /**
   * Durée de visionnage totale estimée, en heures.
   */
  estimated_duration_hours?: number | null;
  /**
   * Collection directement liée à ce parcours.
   */
  linked_collection?: (number | null) | Collection;
  /**
   * Rendre le parcours visible sur le site public.
   */
  is_published?: boolean | null;
  display_order?: number | null;
  steps?: {
    docs?: (number | PathwayStep)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathway-steps".
 */
export interface PathwayStep {
  id: number;
  pathway: number | Pathway;
  media_item: number | MediaItem;
  /**
   * Ordre de l'étape dans le parcours. Commence à 1. Fixe.
   */
  position: number;
  /**
   * Titre éditorial de l'étape (ex : "L'étincelle" plutôt que le titre du film).
   */
  step_title?: string | null;
  /**
   * 150 à 300 mots. Contexte, apport de l'oeuvre dans le parcours, ouverture sur la suite.
   */
  step_editorial: string;
  /**
   * Note factuelle optionnelle. 50 mots maximum.
   */
  step_context?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-items".
 */
export interface CollectionItem {
  id: number;
  collection: number | Collection;
  media_item: number | MediaItem;
  /**
   * Note éditoriale sur l'oeuvre dans cette collection.
   */
  item_note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-watched-items".
 */
export interface UserWatchedItem {
  id: number;
  user: number | Customer;
  media_item: number | MediaItem;
  /**
   * Date de visionnage saisie par l'utilisateur.
   */
  watched_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-collection-progress".
 */
export interface UserCollectionProgress {
  id: number;
  user: number | Customer;
  collection: number | Collection;
  items_seen: number;
  items_total: number;
  percentage: number;
  is_completed: boolean;
  completed_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-pathway-progress".
 */
export interface UserPathwayProgress {
  id: number;
  user: number | Customer;
  pathway: number | Pathway;
  steps_completed: number;
  steps_total: number;
  percentage: number;
  is_completed: boolean;
  completed_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: number;
  /**
   * Identifiant stable, ne pas modifier après création.
   */
  slug: string;
  title: string;
  description?: string | null;
  /**
   * URL de l'icône du badge (chemin public ou URL externe).
   */
  icon_url?: string | null;
  condition_type:
    | 'first_collection'
    | 'first_pathway'
    | 'milestone_10'
    | 'milestone_50'
    | 'milestone_100'
    | 'milestone_250'
    | 'milestone_500';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-badges".
 */
export interface UserBadge {
  id: number;
  user: number | Customer;
  badge: number | Badge;
  earned_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media-types';
        value: number | MediaType;
      } | null)
    | ({
        relationTo: 'media-items';
        value: number | MediaItem;
      } | null)
    | ({
        relationTo: 'external-ids';
        value: number | ExternalId;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'collection-items';
        value: number | CollectionItem;
      } | null)
    | ({
        relationTo: 'pathways';
        value: number | Pathway;
      } | null)
    | ({
        relationTo: 'pathway-steps';
        value: number | PathwayStep;
      } | null)
    | ({
        relationTo: 'user-watched-items';
        value: number | UserWatchedItem;
      } | null)
    | ({
        relationTo: 'user-collection-progress';
        value: number | UserCollectionProgress;
      } | null)
    | ({
        relationTo: 'user-pathway-progress';
        value: number | UserPathwayProgress;
      } | null)
    | ({
        relationTo: 'badges';
        value: number | Badge;
      } | null)
    | ({
        relationTo: 'user-badges';
        value: number | UserBadge;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  pseudo?: T;
  disabled?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-types_select".
 */
export interface MediaTypesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  display_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-items_select".
 */
export interface MediaItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  original_title?: T;
  year?: T;
  release_date?: T;
  duration?: T;
  synopsis?: T;
  poster_url?: T;
  media_type?: T;
  tmdb_id?: T;
  imdb_id?: T;
  director?: T;
  cast?: T;
  source_of_truth?: T;
  source_last_synced_at?: T;
  source_expires_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-ids_select".
 */
export interface ExternalIdsSelect<T extends boolean = true> {
  media_item?: T;
  provider?: T;
  external_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  short_description?: T;
  editorial_note?: T;
  type?: T;
  accessibility_level?: T;
  cover_image_url?: T;
  is_open?: T;
  is_published?: T;
  linked_pathway?: T;
  display_order?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-items_select".
 */
export interface CollectionItemsSelect<T extends boolean = true> {
  collection?: T;
  media_item?: T;
  item_note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathways_select".
 */
export interface PathwaysSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  introduction?: T;
  type?: T;
  accessibility_level?: T;
  estimated_duration_hours?: T;
  linked_collection?: T;
  is_published?: T;
  display_order?: T;
  steps?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pathway-steps_select".
 */
export interface PathwayStepsSelect<T extends boolean = true> {
  pathway?: T;
  media_item?: T;
  position?: T;
  step_title?: T;
  step_editorial?: T;
  step_context?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-watched-items_select".
 */
export interface UserWatchedItemsSelect<T extends boolean = true> {
  user?: T;
  media_item?: T;
  watched_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-collection-progress_select".
 */
export interface UserCollectionProgressSelect<T extends boolean = true> {
  user?: T;
  collection?: T;
  items_seen?: T;
  items_total?: T;
  percentage?: T;
  is_completed?: T;
  completed_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-pathway-progress_select".
 */
export interface UserPathwayProgressSelect<T extends boolean = true> {
  user?: T;
  pathway?: T;
  steps_completed?: T;
  steps_total?: T;
  percentage?: T;
  is_completed?: T;
  completed_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  icon_url?: T;
  condition_type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-badges_select".
 */
export interface UserBadgesSelect<T extends boolean = true> {
  user?: T;
  badge?: T;
  earned_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}